name: build-docker

on: [push]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: List files
        run: ls -la
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: thomctrs
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            thomctrs/Docker-getting:latest
            thomctrs/Docker-getting:${{ github.sha }}
